### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by ryu022304** [ryu022304/laravel-test#1]
## 概要
Laravelを用いて、PHPの復習とテスト駆動開発をやってみる

## タスク
- [ ] 'api/customers'にGETメソッドでアクセスできる
- [ ] 'api/customers'にPOSTメソッドでアクセスできる
- [ ] 'api/customers/{customer_id}'にGETメソッドでアクセスできる
- [ ] 'api/customers/{customer_id}'にPUTメソッドでアクセスできる
- [ ] 'api/customers/{customer_id}'にDELETEメソッドでアクセスできる
- [ ] 'api/reports'にGETメソッドでアクセスできる
- [ ] 'api/reports'にPOSTメソッドでアクセスできる
- [ ] 'api/reports/{report_id}'にGETメソッドでアクセスできる
- [ ] 'api/reports/{report_id}'にPUTメソッドでアクセスできる
- [ ] 'api/reports/{report_id}'にDELETEメソッドでアクセスできる
 
#### 備考
下記を参考にしている
[LaravelでTDDを体験しよう #phpcon2018](https://speakerdeck.com/omoon/laraveldetddwoti-yan-siyou-number-phpcon2018)
